### GET JWT token
POST http://localhost:8080/academics/api/login/token
Content-Type: application/x-www-form-urlencoded

id=s1&password=1

### Who am I?
GET http://localhost:8080/academics/api/login/claims
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzMSIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJTdHVkZW50Il0sImV4cCI6MTYwNDY3ODgxN30.Gt080ThjQPmyQMJl5RuDuvBjx_61wpfS9CtPa3Rf-yIj3EumOLS35y6sDi-J6uosph00rOVUKrLzXwx5HS7sp8PlYJretDS887j4QCfXcJdwF5Vh2tqGQYv_kKgJwtNijvaCzuUgkBWASzkMZCGwQE9A58vHT9dvgoI15OHEpfiIbJrzOQqGeg_2tQm5anwviYBIqV-MCUSjya9uPO3GX2ldB66QeAj58pXrs_-3k2skDVXaEEAbLRrt_Pkw8QTVNV_UWVp9gTnvI5VuPuGdwKowDGM1KPspgr8BKSMQlul6TGPvIZTTHdN0HgBHBF1dp1GFoek2ZjWrf6otanL3yw


##### Students
GET http://localhost:8080/academics/api/students
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzMSIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJTdHVkZW50Il0sImV4cCI6MTYwNDY3ODgxN30.Gt080ThjQPmyQMJl5RuDuvBjx_61wpfS9CtPa3Rf-yIj3EumOLS35y6sDi-J6uosph00rOVUKrLzXwx5HS7sp8PlYJretDS887j4QCfXcJdwF5Vh2tqGQYv_kKgJwtNijvaCzuUgkBWASzkMZCGwQE9A58vHT9dvgoI15OHEpfiIbJrzOQqGeg_2tQm5anwviYBIqV-MCUSjya9uPO3GX2ldB66QeAj58pXrs_-3k2skDVXaEEAbLRrt_Pkw8QTVNV_UWVp9gTnvI5VuPuGdwKowDGM1KPspgr8BKSMQlul6TGPvIZTTHdN0HgBHBF1dp1GFoek2ZjWrf6otanL3yw
###
POST http://localhost:8080/academics/api/students
Content-Type: application/json

{
 "email": "dae.ei.ipleiria@gmail.com",
 "name": "Joaquina",
 "id": "1234567",
 "password": "Joaquina",
 "courseCode":"1",
 "courseName":"EI"
}
##### Courses
GET http://localhost:8080/academics/api/courses
Accept: application/json

##### GetStudentDetails s1
GET http://localhost:8080/academics/api/students/s1
Accept: application/json

##### GetStudentDetails s2
GET http://localhost:8080/academics/api/students/s2
Accept: application/json


##### GetStudentSubjects s1
GET http://localhost:8080/academics/api/students/s2/subjects
Accept: application/json

#### GetTeachers
GET http://localhost:8080/academics/api/teachers
