##### Students
GET http://localhost:8080/academics/api/students
Accept: application/json
###
POST http://localhost:8080/academics/api/students
Content-Type: application/json

{
 "email": "dae.ei.ipleiria@gmail.com",
 "name": "Joaquina",
 "id": "1234567",
 "password": "Joaquina",
 "courseCode":"1",
 "courseName":"EI"
}
##### Courses
GET http://localhost:8080/academics/api/courses
Accept: application/json

##### GetStudentDetails s1
GET http://localhost:8080/academics/api/students/s1
Accept: application/json

##### GetStudentDetails s2
GET http://localhost:8080/academics/api/students/s2
Accept: application/json


##### GetStudentSubjects s1
GET http://localhost:8080/academics/api/students/s2/subjects
Accept: application/json